In [1]:
import pandas as pd

In [2]:
January = pd.read_csv('CSV_files/Jan19.csv')
January.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,201,2019-01-01 03:09:09.7110,2019-01-01 03:12:30.8790,3183,Exchange Place,40.716247,-74.033459,3214,Essex Light Rail,40.712774,-74.036486,29612,Subscriber,1993,1
1,505,2019-01-01 05:18:00.1060,2019-01-01 05:26:25.9050,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29213,Subscriber,1972,2
2,756,2019-01-01 10:36:33.3400,2019-01-01 10:49:10.2600,3183,Exchange Place,40.716247,-74.033459,3192,Liberty Light Rail,40.711242,-74.055701,26164,Subscriber,1985,1
3,1575,2019-01-01 12:43:38.6430,2019-01-01 13:09:54.5280,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29672,Customer,1969,0
4,1566,2019-01-01 12:43:39.6010,2019-01-01 13:09:46.5100,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29522,Customer,1969,0

In [4]:
February = pd.read_csv('CSV_files/Feb19.csv')
February.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,142,2019-02-01 15:35:02.0820,2019-02-01 15:37:24.1360,3183,Exchange Place,40.716247,-74.033459,3639,Harborside,40.719252,-74.034234,29677,Subscriber,1963,1
1,223,2019-02-01 17:00:46.8900,2019-02-01 17:04:30.5500,3183,Exchange Place,40.716247,-74.033459,3681,Grand St,40.715178,-74.037683,26234,Subscriber,1992,2
2,106,2019-02-01 17:08:01.3260,2019-02-01 17:09:47.4400,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,29588,Subscriber,1960,1
3,370,2019-02-01 17:09:31.2100,2019-02-01 17:15:41.6550,3183,Exchange Place,40.716247,-74.033459,3211,Newark Ave,40.721525,-74.046305,29250,Subscriber,1976,1
4,315,2019-02-01 17:19:53.2490,2019-02-01 17:25:09.1400,3183,Exchange Place,40.716247,-74.033459,3273,Manila & 1st,40.721651,-74.042884,29586,Subscriber,1980,1

In [5]:
March = pd.read_csv('CSV_files/Mar19.csv')
March.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,306,2019-03-01 06:47:08.2110,2019-03-01 06:52:14.7150,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,26272,Subscriber,1989,1
1,123,2019-03-01 07:30:53.0220,2019-03-01 07:32:56.7770,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,26192,Subscriber,1966,1
2,328,2019-03-01 08:18:30.4030,2019-03-01 08:23:59.0590,3183,Exchange Place,40.716247,-74.033459,3213,Van Vorst Park,40.718489,-74.047727,26226,Subscriber,1971,2
3,95,2019-03-01 11:04:47.2020,2019-03-01 11:06:22.8130,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,26204,Subscriber,1985,1
4,169,2019-03-01 11:51:29.4170,2019-03-01 11:54:19.2120,3183,Exchange Place,40.716247,-74.033459,3639,Harborside,40.719252,-74.034234,29449,Subscriber,1971,1

In [6]:
April = pd.read_csv('CSV_files/Apr19.csv')
April.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,107,2019-04-01 07:48:04.7540,2019-04-01 07:49:52.3590,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,29536,Subscriber,1966,1
1,493,2019-04-01 12:41:09.6540,2019-04-01 12:49:23.0290,3183,Exchange Place,40.716247,-74.033459,3187,Warren St,40.721124,-74.038051,26191,Customer,1990,1
2,512,2019-04-01 14:27:07.9400,2019-04-01 14:35:40.9370,3183,Exchange Place,40.716247,-74.033459,3202,Newport PATH,40.727224,-74.033759,29302,Subscriber,1987,2
3,196,2019-04-01 15:07:38.1510,2019-04-01 15:10:54.6260,3183,Exchange Place,40.716247,-74.033459,3214,Essex Light Rail,40.712774,-74.036486,26220,Subscriber,1989,1
4,463,2019-04-01 16:19:24.6940,2019-04-01 16:27:08.6450,3183,Exchange Place,40.716247,-74.033459,3273,Manila & 1st,40.721651,-74.042884,26228,Subscriber,1995,1

In [7]:
May = pd.read_csv('CSV_files/May19.csv')
May.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,311,2019-05-01 00:07:36.4670,2019-05-01 00:12:47.6350,3185,City Hall,40.717733,-74.043845,3279,Dixon Mills,40.721630,-74.049968,29224,Subscriber,1988,1
1,538,2019-05-01 00:08:29.2840,2019-05-01 00:17:27.9410,3681,Grand St,40.715178,-74.037683,3203,Hamilton Park,40.727596,-74.044247,26170,Subscriber,1974,1
2,178,2019-05-01 00:39:36.4750,2019-05-01 00:42:34.9640,3638,Washington St,40.724294,-74.035483,3639,Harborside,40.719252,-74.034234,29517,Subscriber,1988,1
3,317,2019-05-01 01:24:28.0220,2019-05-01 01:29:45.5730,3206,Hilltop,40.731169,-74.057574,3212,Christ Hospital,40.734786,-74.050444,29606,Subscriber,1986,2
4,354,2019-05-01 01:54:39.6660,2019-05-01 02:00:34.1750,3639,Harborside,40.719252,-74.034234,3202,Newport PATH,40.727224,-74.033759,26224,Customer,1986,2

In [8]:
June = pd.read_csv('CSV_files/Jun19.csv')
June.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,316,2019-06-01 00:05:55.7210,2019-06-01 00:11:11.9940,3187,Warren St,40.721124,-74.038051,3199,Newport Pkwy,40.728745,-74.032108,29677,Subscriber,1993,1
1,280,2019-06-01 00:08:09.0920,2019-06-01 00:12:50.0730,3185,City Hall,40.717733,-74.043845,3267,Morris Canal,40.712419,-74.038526,29571,Subscriber,1984,1
2,2162,2019-06-01 00:13:11.8800,2019-06-01 00:49:14.3640,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,26208,Customer,1969,0
3,2184,2019-06-01 00:13:30.1110,2019-06-01 00:49:54.2250,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,29487,Customer,1969,0
4,139,2019-06-01 00:13:31.8520,2019-06-01 00:15:51.7880,3207,Oakland Ave,40.737604,-74.052478,3207,Oakland Ave,40.737604,-74.052478,29592,Subscriber,1994,1

In [9]:
July = pd.read_csv('CSV_files/Jul19.csv')
July.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1793,2019-07-01 00:00:36.6150,2019-07-01 00:30:30.5940,3186,Grove St PATH,40.719586,-74.043117,3198,Heights Elevator,40.748716,-74.040443,29595,Subscriber,1978,1
1,434,2019-07-01 00:02:54.6150,2019-07-01 00:10:09.0370,3206,Hilltop,40.731169,-74.057574,3280,Astor Place,40.719282,-74.071262,29647,Subscriber,1988,1
2,251,2019-07-01 00:03:27.5670,2019-07-01 00:07:38.6080,3186,Grove St PATH,40.719586,-74.043117,3205,JC Medical Center,40.716540,-74.049638,26271,Subscriber,1986,1
3,636,2019-07-01 00:03:56.1690,2019-07-01 00:14:32.4180,3206,Hilltop,40.731169,-74.057574,3281,Leonard Gordon Park,40.745910,-74.057271,26225,Customer,1996,2
4,623,2019-07-01 00:04:16.2060,2019-07-01 00:14:40.0500,3206,Hilltop,40.731169,-74.057574,3281,Leonard Gordon Park,40.745910,-74.057271,29230,Customer,1989,1

In [10]:
August = pd.read_csv('CSV_files/Aug19.csv')
August.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,261,2019-08-01 00:14:55.9900,2019-08-01 00:19:17.4780,3205,JC Medical Center,40.716540,-74.049638,3192,Liberty Light Rail,40.711242,-74.055701,26268,Subscriber,1980,1
1,172,2019-08-01 00:23:06.9910,2019-08-01 00:25:59.1480,3279,Dixon Mills,40.721630,-74.049968,3186,Grove St PATH,40.719586,-74.043117,26162,Subscriber,1996,1
2,525,2019-08-01 00:23:28.6170,2019-08-01 00:32:13.7000,3199,Newport Pkwy,40.728745,-74.032108,3203,Hamilton Park,40.727596,-74.044247,29279,Subscriber,1991,1
3,219,2019-08-01 00:32:36.1410,2019-08-01 00:36:15.2730,3187,Warren St,40.721124,-74.038051,3185,City Hall,40.717733,-74.043845,29598,Subscriber,1988,1
4,262,2019-08-01 00:41:26.6700,2019-08-01 00:45:49.3530,3186,Grove St PATH,40.719586,-74.043117,3272,Jersey & 3rd,40.723332,-74.045953,26162,Subscriber,1960,1

In [11]:
September = pd.read_csv('CSV_files/Sep19.csv')
September.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,145,2019-09-01 00:00:37.6920,2019-09-01 00:03:03.0100,3640,Journal Square,40.733670,-74.062500,3206,Hilltop,40.731169,-74.057574,29303,Subscriber,1991,1
1,212,2019-09-01 00:03:00.6000,2019-09-01 00:06:33.3420,3194,McGinley Square,40.725340,-74.067622,3679,Bergen Ave,40.722104,-74.071455,29297,Subscriber,1993,2
2,569,2019-09-01 00:07:13.0020,2019-09-01 00:16:42.8610,3214,Essex Light Rail,40.712774,-74.036486,3184,Paulus Hook,40.714145,-74.033552,29435,Customer,1977,1
3,1380,2019-09-01 00:07:25.3350,2019-09-01 00:30:26.1640,3214,Essex Light Rail,40.712774,-74.036486,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,29509,Subscriber,1965,1
4,1346,2019-09-01 00:07:56.4670,2019-09-01 00:30:22.5440,3214,Essex Light Rail,40.712774,-74.036486,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,29226,Subscriber,1968,2

In [12]:
October = pd.read_csv('CSV_files/Oct19.csv')
October.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,892,2019-10-01 00:20:05.0140,2019-10-01 00:34:57.3800,3275,Columbus Drive,40.718355,-74.038914,3280,Astor Place,40.719282,-74.071262,29544,Subscriber,1976,1
1,374,2019-10-01 00:43:48.8790,2019-10-01 00:50:03.8190,3211,Newark Ave,40.721525,-74.046305,3791,Hoboken Ave at Monmouth St,40.735208,-74.046964,29536,Subscriber,1984,1
2,170,2019-10-01 01:35:51.8630,2019-10-01 01:38:42.5470,3194,McGinley Square,40.725340,-74.067622,3679,Bergen Ave,40.722104,-74.071455,26304,Subscriber,1986,1
3,946,2019-10-01 02:55:53.4000,2019-10-01 03:11:40.2710,3272,Jersey & 3rd,40.723332,-74.045953,3679,Bergen Ave,40.722104,-74.071455,29496,Customer,1969,0
4,517,2019-10-01 03:10:16.1290,2019-10-01 03:18:53.6350,3206,Hilltop,40.731169,-74.057574,3210,Pershing Field,40.742677,-74.051789,26205,Subscriber,1969,1

In [13]:
November = pd.read_csv('CSV_files/Nov19.csv')
November.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,260,2019-11-01 00:02:53.8860,2019-11-01 00:07:14.6450,3186,Grove St PATH,40.719586,-74.043117,3203,Hamilton Park,40.727596,-74.044247,26314,Subscriber,1964,1
1,285,2019-11-01 00:05:38.6360,2019-11-01 00:10:24.1930,3206,Hilltop,40.731169,-74.057574,3212,Christ Hospital,40.734786,-74.050444,26238,Subscriber,1986,2
2,501,2019-11-01 00:05:43.6310,2019-11-01 00:14:05.4810,3186,Grove St PATH,40.719586,-74.043117,3192,Liberty Light Rail,40.711242,-74.055701,29645,Subscriber,1995,1
3,556,2019-11-01 00:07:57.0550,2019-11-01 00:17:13.9010,3209,Brunswick St,40.724176,-74.050656,3678,Fairmount Ave,40.725726,-74.071959,29221,Customer,1992,1
4,321,2019-11-01 00:11:44.5660,2019-11-01 00:17:05.5930,3273,Manila & 1st,40.721651,-74.042884,3273,Manila & 1st,40.721651,-74.042884,29591,Subscriber,1988,1

In [15]:
citibikes19 = pd.concat([January, February, March, April, May, June, July, August, September, October, November])
citibikes19

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,201,2019-01-01 03:09:09.7110,2019-01-01 03:12:30.8790,3183,Exchange Place,40.716247,-74.033459,3214,Essex Light Rail,40.712774,-74.036486,29612,Subscriber,1993,1
1,505,2019-01-01 05:18:00.1060,2019-01-01 05:26:25.9050,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29213,Subscriber,1972,2
2,756,2019-01-01 10:36:33.3400,2019-01-01 10:49:10.2600,3183,Exchange Place,40.716247,-74.033459,3192,Liberty Light Rail,40.711242,-74.055701,26164,Subscriber,1985,1
3,1575,2019-01-01 12:43:38.6430,2019-01-01 13:09:54.5280,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29672,Customer,1969,0
4,1566,2019-01-01 12:43:39.6010,2019-01-01 13:09:46.5100,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29522,Customer,1969,0
5,737,2019-01-01 12:56:53.2040,2019-01-01 13:09:11.0400,3183,Exchange Place,40.716247,-74.033459,3205,JC Medical Center,40.716540,-74.049638,29447,Subscriber,1993,1
6,917,2019-01-01 13:03:44.7760,2019-01-01 13:19:02.7690,3183,Exchange Place,40.716247,-74.033459,3277,Communipaw & Berry Lane,40.714358,-74.066611,29299,Subscriber,1986,1
7,3248,2019-01-01 13:12:03.1280,2019-01-01 14:06:12.0400,3183,Exchange Place,40.716247,-74.033459,3196,Riverview Park,40.744319,-74.043991,29495,Subscriber,1992,1
8,3168,2019-01-01 13:13:12.0450,2019-01-01 14:06:00.4110,3183,Exchange Place,40.716247,-74.033459,3196,Riverview Park,40.744319,-74.043991,26312,Customer,1969,0
9,353,2019-01-01 17:07:44.6670,2019-01-01 17:13:38.2640,3183,Exchange Place,40.716247,-74.033459,3202,Newport PATH,40.727224,-74.033759,26212,Subscriber,1994,1
10,503,2019-01-01 17:34:50.9580,2019-01-01 17:43:14.3190,3183,Exchange Place,40.716247,-74.033459,3202,Newport PATH,40.727224,-74.033759,29661,Customer,1992,1
11,285,2019-01-01 18:06:03.1680,2019-01-01 18:10:48.5380,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,29544,Subscriber,1990,1
12,229,2019-01-01 20:05:04.5760,2019-01-01 20:08:53.8630,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29307,Subscriber,1996,1
13,211,2019-01-01 21:04:58.8810,2019-01-01 21:08:30.5600,3183,Exchange Place,40.716247,-74.033459,3214,Essex Light Rail,40.712774,-74.036486,29217,Subscriber,1993,1
14,111,2019-01-01 21:52:09.2980,2019-01-01 21:54:00.4550,3183,Exchange Place,40.716247,-74.033459,3183,Exchange Place,40.716247,-74.033459,29453,Subscriber,1987,1
15,663,2019-01-01 21:54:27.9360,2019-01-01 22:05:31.8800,3183,Exchange Place,40.716247,-74.033459,3183,Exchange Place,40.716247,-74.033459,29286,Subscriber,1987,1
16,451,2019-01-02 00:08:06.5510,2019-01-02 00:15:38.0940,3183,Exchange Place,40.716247,-74.033459,3681,Grand St,40.715178,-74.037683,29453,Subscriber,1960,1
17,742,2019-01-02 07:17:22.2050,2019-01-02 07:29:45.1610,3183,Exchange Place,40.716247,-74.033459,3270,Jersey & 6th St,40.725289,-74.045572,29608,Subscriber,1977,1
18,121,2019-01-02 07:55:53.5040,2019-01-02 07:57:54.9410,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,29122,Subscriber,1966,1
19,284,2019-01-02 08:09:38.7570,2019-01-02 08:14:23.6940,3183,Exchange Place,40.716247,-74.033459,3185,City Hall,40.717733,-74.043845,26202,Subscriber,1986,1
20,120,2019-01-02 08:18:36.9570,2019-01-02 08:20:37.9440,3183,Exchange Place,40.716247,-74.033459,3681,Grand St,40.715178,-74.037683,29602,Subscriber,1975,2
21,75,2019-01-02 08:25:25.9610,2019-01-02 08:26:41.4140,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,29228,Subscriber,1975,1
22,113,2019-01-02 08:47:54.6750,2019-01-02 08:49:47.9970,3183,Exchange Place,40.716247,-74.033459,3639,Harborside,40.719252,-74.034234,26278,Subscriber,1969,1
23,187,2019-01-02 10:39:26.6940,2019-01-02 10:42:34.6680,3183,Exchange Place,40.716247,-74.033459,3186,Grove St PATH,40.719586,-74.043117,26288,Subscriber,1982,1
24,259,2019-01-02 10:57:36.4500,2019-01-02 11:01:55.7620,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,29641,Subscriber,1984,1
25,969,2019-01-02 11:45:40.3390,2019-01-02 12:01:49.4380,3183,Exchange Place,40.716247,-74.033459,3207,Oakland Ave,40.737604,-74.052478,29252,Subscriber,1981,1
26,355,2019-01-02 12:12:43.7790,2019-01-02 12:18:39.1990,3183,Exchange Place,40.716247,-74.033459,3272,Jersey & 3rd,40.723332,-74.045953,29484,Subscriber,1988,1
27,288,2019-01-02 12:22:12.8260,2019-01-02 12:27:01.5450,3183,Exchange Place,40.716247,-74.033459,3186,Grove St PATH,40.719586,-74.043117,29293,Subscriber,1981,2
28,2602,2019-01-02 12:27:14.6360,2019-01-02 13:10:37.2240,3183,Exchange Place,40.716247,-74.033459,3183,Exchange Place,40.716247,-74.033459,29286,Customer,1969,0
29,1360,2019-01-02 12:32:56.9960,2019-01-02 12:55:37.7920,3183,Exchange Place,40.716247,-74.033459,3183,Exchange Place,40.716247,-74.033459,26208,Customer,1971,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30767,315,2019-11-30 21:52:48.3460,2019-11-30 21:58:03.5810,3195,Sip Ave,40.730897,-74.063913,3679,Bergen Ave,40.722104,-74.071455,29123,Subscriber,1987,1
30768,348,2019-11-30 21:53:16.3790,2019-11-30 21:59:04.4700,3202,Newport PATH,40.727224,-74.033759,3203,Hamilton Park,40.727596,-74.044247,29445,Customer,2000,1
30769,694,2019-11-30 22:03:17.5430,2019-11-30 22:14:52.2530,3186,Grove St PATH,40.719586,-74.043117,3268,Lafayette Park,40.713464,-74.062859,29228,Subscriber,1982,1
30770,298,2019-11-30 22:07:04.1290,2019-11-30 22:12:02.6610,3267,Morris Canal,40.712419,-74.038526,3186,Grove St PATH,40.719586,-74.043117,29527,Subscriber,1976,1
30771,132,2019-11-30 22:14:33.2860,2019-11-30 22:16:45.9020,3272,Jersey & 3rd,40.723332,-74.045953,3213,Van Vorst Park,40.718489,-74.047727,29552,Subscriber,1985,1
30772,340,2019-11-30 22:18:47.2390,2019-11-30 22:24:28.1130,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,26263,Subscriber,1988,1
30773,170,2019-11-30 22:20:47.7350,2019-11-30 22:23:37.9990,3194,McGinley Square,40.725340,-74.067622,3195,Sip Ave,40.730897,-74.063913,26227,Subscriber,1993,1
30774,144,2019-11-30 22:22:58.5860,2019-11-30 22:25:23.5540,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,3639,Harborside,40.719252,-74.034234,26310,Subscriber,1991,2
30775,136,2019-11-30 22:23:09.2120,2019-11-30 22:25:25.8600,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,3639,Harborside,40.719252,-74.034234,29583,Subscriber,1993,1
30776,325,2019-11-30 22:23:32.3370,2019-11-30 22:28:58.0440,3678,Fairmount Ave,40.725726,-74.071959,3195,Sip Ave,40.730897,-74.063913,26267,Subscriber,1994,2
30777,210,2019-11-30 22:26:43.5270,2019-11-30 22:30:13.7290,3186,Grove St PATH,40.719586,-74.043117,3279,Dixon Mills,40.721630,-74.049968,29612,Subscriber,1984,2
30778,393,2019-11-30 22:27:05.4000,2019-11-30 22:33:38.7560,3193,Lincoln Park,40.724605,-74.078406,3195,Sip Ave,40.730897,-74.063913,26272,Subscriber,1983,1
30779,502,2019-11-30 22:27:53.2600,2019-11-30 22:36:16.1300,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,29524,Subscriber,1987,1
30780,505,2019-11-30 22:28:06.0000,2019-11-30 22:36:31.2380,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,29594,Customer,1969,0
30781,1628,2019-11-30 22:28:53.4980,2019-11-30 22:56:02.0440,3211,Newark Ave,40.721525,-74.046305,3681,Grand St,40.715178,-74.037683,26281,Subscriber,1980,1
30782,523,2019-11-30 22:31:28.7530,2019-11-30 22:40:12.4950,3640,Journal Square,40.733670,-74.062500,3210,Pershing Field,40.742677,-74.051789,26152,Subscriber,1990,1
30783,153,2019-11-30 22:44:52.7150,2019-11-30 22:47:25.7150,3186,Grove St PATH,40.719586,-74.043117,3213,Van Vorst Park,40.718489,-74.047727,29527,Subscriber,1977,1
30784,146,2019-11-30 23:03:25.9760,2019-11-30 23:05:52.5800,3186,Grove St PATH,40.719586,-74.043117,3279,Dixon Mills,40.721630,-74.049968,26182,Subscriber,1975,1
30785,288,2019-11-30 23:06:00.0150,2019-11-30 23:10:48.2690,3186,Grove St PATH,40.719586,-74.043117,3205,JC Medical Center,40.716540,-74.049638,29676,Subscriber,1986,2
30786,263,2019-11-30 23:06:27.3040,2019-11-30 23:10:51.0000,3186,Grove St PATH,40.719586,-74.043117,3205,JC Medical Center,40.716540,-74.049638,26269,Subscriber,1983,1
30787,391,2019-11-30 23:11:41.5040,2019-11-30 23:18:12.8600,3213,Van Vorst Park,40.718489,-74.047727,3192,Liberty Light Rail,40.711242,-74.055701,29466,Subscriber,1984,1
30788,240,2019-11-30 23:12:49.4890,2019-11-30 23:16:50.1430,3276,Marin Light Rail,40.714584,-74.042817,3186,Grove St PATH,40.719586,-74.043117,29265,Subscriber,1970,1
30789,1128,2019-11-30 23:21:38.0230,2019-11-30 23:40:26.7860,3202,Newport PATH,40.727224,-74.033759,3202,Newport PATH,40.727224,-74.033759,29659,Subscriber,1989,2
30790,344,2019-11-30 23:22:06.6910,2019-11-30 23:27:51.0870,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,3276,Marin Light Rail,40.714584,-74.042817,29591,Customer,1991,2
30791,11992,2019-11-30 23:25:26.7530,2019-12-01 02:45:18.9070,3277,Communipaw & Berry Lane,40.714358,-74.066611,3277,Communipaw & Berry Lane,40.714358,-74.066611,26212,Customer,1969,0
30792,77,2019-11-30 23:30:07.7850,2019-11-30 23:31:25.7730,3638,Washington St,40.724294,-74.035483,3202,Newport PATH,40.727224,-74.033759,29492,Subscriber,1979,1
30793,145,2019-11-30 23:40:45.3790,2019-11-30 23:43:10.5660,3211,Newark Ave,40.721525,-74.046305,3278,Monmouth and 6th,40.725685,-74.048790,40971,Subscriber,1978,1
30794,99,2019-11-30 23:41:55.3310,2019-11-30 23:43:34.3320,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,3639,Harborside,40.719252,-74.034234,26198,Subscriber,1991,1
30795,594,2019-11-30 23:52:50.2410,2019-12-01 00:02:44.2960,3213,Van Vorst Park,40.718489,-74.047727,3639,Harborside,40.719252,-74.034234,29527,Subscriber,1981,1
30796,329,2019-11-30 23:56:27.6680,2019-12-01 00:01:57.0120,3185,City Hall,40.717733,-74.043845,3267,Morris Canal,40.712419,-74.038526,26163,Subscriber,1977,1

In [16]:
citibikes19.to_csv('2019_citibike_data.csv', sep = ',')